/*
 * This file is generated by jOOQ.
 */
package com.chen.zhou.liang.lancet.storage.orm.tables.records;


import com.chen.zhou.liang.lancet.storage.orm.tables.Cards;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardsRecord extends UpdatableRecordImpl<CardsRecord> implements Record6<Integer, String, String, String, Float, String> {

    private static final long serialVersionUID = -753747970;

    /**
     * Setter for <code>cards.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cards.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cards.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cards.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cards.idcard</code>.
     */
    public void setIdcard(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cards.idcard</code>.
     */
    public String getIdcard() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cards.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cards.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cards.credit</code>.
     */
    public void setCredit(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>cards.credit</code>.
     */
    public Float getCredit() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>cards.regtime</code>.
     */
    public void setRegtime(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cards.regtime</code>.
     */
    public String getRegtime() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Float, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, Float, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Cards.CARDS.ID;
    }

    @Override
    public Field<String> field2() {
        return Cards.CARDS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Cards.CARDS.IDCARD;
    }

    @Override
    public Field<String> field4() {
        return Cards.CARDS.PHONE;
    }

    @Override
    public Field<Float> field5() {
        return Cards.CARDS.CREDIT;
    }

    @Override
    public Field<String> field6() {
        return Cards.CARDS.REGTIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getIdcard();
    }

    @Override
    public String component4() {
        return getPhone();
    }

    @Override
    public Float component5() {
        return getCredit();
    }

    @Override
    public String component6() {
        return getRegtime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getIdcard();
    }

    @Override
    public String value4() {
        return getPhone();
    }

    @Override
    public Float value5() {
        return getCredit();
    }

    @Override
    public String value6() {
        return getRegtime();
    }

    @Override
    public CardsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CardsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CardsRecord value3(String value) {
        setIdcard(value);
        return this;
    }

    @Override
    public CardsRecord value4(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public CardsRecord value5(Float value) {
        setCredit(value);
        return this;
    }

    @Override
    public CardsRecord value6(String value) {
        setRegtime(value);
        return this;
    }

    @Override
    public CardsRecord values(Integer value1, String value2, String value3, String value4, Float value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardsRecord
     */
    public CardsRecord() {
        super(Cards.CARDS);
    }

    /**
     * Create a detached, initialised CardsRecord
     */
    public CardsRecord(Integer id, String name, String idcard, String phone, Float credit, String regtime) {
        super(Cards.CARDS);

        set(0, id);
        set(1, name);
        set(2, idcard);
        set(3, phone);
        set(4, credit);
        set(5, regtime);
    }
}
