/*
 * This file is generated by jOOQ.
 */
package com.chen.zhou.liang.lancet.storage.orm.tables.records;


import com.chen.zhou.liang.lancet.storage.orm.tables.Loginmsg;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoginmsgRecord extends UpdatableRecordImpl<LoginmsgRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -1789110210;

    /**
     * Setter for <code>loginmsg.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>loginmsg.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>loginmsg.passwordhash</code>.
     */
    public void setPasswordhash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>loginmsg.passwordhash</code>.
     */
    public String getPasswordhash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>loginmsg.salt</code>.
     */
    public void setSalt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>loginmsg.salt</code>.
     */
    public String getSalt() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Loginmsg.LOGINMSG.USERNAME;
    }

    @Override
    public Field<String> field2() {
        return Loginmsg.LOGINMSG.PASSWORDHASH;
    }

    @Override
    public Field<String> field3() {
        return Loginmsg.LOGINMSG.SALT;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String component2() {
        return getPasswordhash();
    }

    @Override
    public String component3() {
        return getSalt();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public String value2() {
        return getPasswordhash();
    }

    @Override
    public String value3() {
        return getSalt();
    }

    @Override
    public LoginmsgRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public LoginmsgRecord value2(String value) {
        setPasswordhash(value);
        return this;
    }

    @Override
    public LoginmsgRecord value3(String value) {
        setSalt(value);
        return this;
    }

    @Override
    public LoginmsgRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoginmsgRecord
     */
    public LoginmsgRecord() {
        super(Loginmsg.LOGINMSG);
    }

    /**
     * Create a detached, initialised LoginmsgRecord
     */
    public LoginmsgRecord(String username, String passwordhash, String salt) {
        super(Loginmsg.LOGINMSG);

        set(0, username);
        set(1, passwordhash);
        set(2, salt);
    }
}
