/*
 * This file is generated by jOOQ.
 */
package com.chen.zhou.liang.lancet.storage.orm.tables.records;


import com.chen.zhou.liang.lancet.storage.orm.tables.Transhistory;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TranshistoryRecord extends TableRecordImpl<TranshistoryRecord> implements Record4<Integer, Float, String, String> {

    private static final long serialVersionUID = -491785334;

    /**
     * Setter for <code>transhistory.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>transhistory.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>transhistory.creditchange</code>.
     */
    public void setCreditchange(Float value) {
        set(1, value);
    }

    /**
     * Getter for <code>transhistory.creditchange</code>.
     */
    public Float getCreditchange() {
        return (Float) get(1);
    }

    /**
     * Setter for <code>transhistory.time</code>.
     */
    public void setTime(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transhistory.time</code>.
     */
    public String getTime() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transhistory.comment</code>.
     */
    public void setComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transhistory.comment</code>.
     */
    public String getComment() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Float, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Float, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Transhistory.TRANSHISTORY.ID;
    }

    @Override
    public Field<Float> field2() {
        return Transhistory.TRANSHISTORY.CREDITCHANGE;
    }

    @Override
    public Field<String> field3() {
        return Transhistory.TRANSHISTORY.TIME;
    }

    @Override
    public Field<String> field4() {
        return Transhistory.TRANSHISTORY.COMMENT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Float component2() {
        return getCreditchange();
    }

    @Override
    public String component3() {
        return getTime();
    }

    @Override
    public String component4() {
        return getComment();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Float value2() {
        return getCreditchange();
    }

    @Override
    public String value3() {
        return getTime();
    }

    @Override
    public String value4() {
        return getComment();
    }

    @Override
    public TranshistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TranshistoryRecord value2(Float value) {
        setCreditchange(value);
        return this;
    }

    @Override
    public TranshistoryRecord value3(String value) {
        setTime(value);
        return this;
    }

    @Override
    public TranshistoryRecord value4(String value) {
        setComment(value);
        return this;
    }

    @Override
    public TranshistoryRecord values(Integer value1, Float value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TranshistoryRecord
     */
    public TranshistoryRecord() {
        super(Transhistory.TRANSHISTORY);
    }

    /**
     * Create a detached, initialised TranshistoryRecord
     */
    public TranshistoryRecord(Integer id, Float creditchange, String time, String comment) {
        super(Transhistory.TRANSHISTORY);

        set(0, id);
        set(1, creditchange);
        set(2, time);
        set(3, comment);
    }
}
