/*
 * This file is generated by jOOQ.
 */
package com.chen.zhou.liang.lancet.storage.orm;


import com.chen.zhou.liang.lancet.storage.orm.tables.Cards;
import com.chen.zhou.liang.lancet.storage.orm.tables.Loginmsg;
import com.chen.zhou.liang.lancet.storage.orm.tables.Transhistory;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 750712998;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>cards</code>.
     */
    public final Cards CARDS = Cards.CARDS;

    /**
     * The table <code>loginmsg</code>.
     */
    public final Loginmsg LOGINMSG = Loginmsg.LOGINMSG;

    /**
     * The table <code>transhistory</code>.
     */
    public final Transhistory TRANSHISTORY = Transhistory.TRANSHISTORY;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Cards.CARDS,
            Loginmsg.LOGINMSG,
            Transhistory.TRANSHISTORY);
    }
}
