/*
 * This file is generated by jOOQ.
 */
package com.chen.zhou.liang.lancet.storage.orm;


import com.chen.zhou.liang.lancet.storage.orm.tables.Cards;
import com.chen.zhou.liang.lancet.storage.orm.tables.Loginmsg;
import com.chen.zhou.liang.lancet.storage.orm.tables.records.CardsRecord;
import com.chen.zhou.liang.lancet.storage.orm.tables.records.LoginmsgRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CardsRecord> PK_CARDS = UniqueKeys0.PK_CARDS;
    public static final UniqueKey<LoginmsgRecord> PK_LOGINMSG = UniqueKeys0.PK_LOGINMSG;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CardsRecord> PK_CARDS = Internal.createUniqueKey(Cards.CARDS, "pk_cards", new TableField[] { Cards.CARDS.ID }, true);
        public static final UniqueKey<LoginmsgRecord> PK_LOGINMSG = Internal.createUniqueKey(Loginmsg.LOGINMSG, "pk_loginmsg", new TableField[] { Loginmsg.LOGINMSG.USERNAME }, true);
    }
}
