/*
 * This file is generated by jOOQ.
 */
package com.chen.zhou.liang.lancet.storage.orm;


import com.chen.zhou.liang.lancet.storage.orm.tables.Cards;
import com.chen.zhou.liang.lancet.storage.orm.tables.Loginmsg;
import com.chen.zhou.liang.lancet.storage.orm.tables.Transhistory;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cards</code>.
     */
    public static final Cards CARDS = Cards.CARDS;

    /**
     * The table <code>loginmsg</code>.
     */
    public static final Loginmsg LOGINMSG = Loginmsg.LOGINMSG;

    /**
     * The table <code>transhistory</code>.
     */
    public static final Transhistory TRANSHISTORY = Transhistory.TRANSHISTORY;
}
