/*
 * This file is generated by jOOQ.
 */
package com.chen.zhou.liang.lancet.storage.orm.tables;


import com.chen.zhou.liang.lancet.storage.orm.DefaultSchema;
import com.chen.zhou.liang.lancet.storage.orm.Keys;
import com.chen.zhou.liang.lancet.storage.orm.tables.records.LoginmsgRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Loginmsg extends TableImpl<LoginmsgRecord> {

    private static final long serialVersionUID = -1315017758;

    /**
     * The reference instance of <code>loginmsg</code>
     */
    public static final Loginmsg LOGINMSG = new Loginmsg();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoginmsgRecord> getRecordType() {
        return LoginmsgRecord.class;
    }

    /**
     * The column <code>loginmsg.username</code>.
     */
    public final TableField<LoginmsgRecord, String> USERNAME = createField(DSL.name("username"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>loginmsg.passwordhash</code>.
     */
    public final TableField<LoginmsgRecord, String> PASSWORDHASH = createField(DSL.name("passwordhash"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>loginmsg.salt</code>.
     */
    public final TableField<LoginmsgRecord, String> SALT = createField(DSL.name("salt"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>loginmsg</code> table reference
     */
    public Loginmsg() {
        this(DSL.name("loginmsg"), null);
    }

    /**
     * Create an aliased <code>loginmsg</code> table reference
     */
    public Loginmsg(String alias) {
        this(DSL.name(alias), LOGINMSG);
    }

    /**
     * Create an aliased <code>loginmsg</code> table reference
     */
    public Loginmsg(Name alias) {
        this(alias, LOGINMSG);
    }

    private Loginmsg(Name alias, Table<LoginmsgRecord> aliased) {
        this(alias, aliased, null);
    }

    private Loginmsg(Name alias, Table<LoginmsgRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Loginmsg(Table<O> child, ForeignKey<O, LoginmsgRecord> key) {
        super(child, key, LOGINMSG);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<LoginmsgRecord> getPrimaryKey() {
        return Keys.PK_LOGINMSG;
    }

    @Override
    public List<UniqueKey<LoginmsgRecord>> getKeys() {
        return Arrays.<UniqueKey<LoginmsgRecord>>asList(Keys.PK_LOGINMSG);
    }

    @Override
    public Loginmsg as(String alias) {
        return new Loginmsg(DSL.name(alias), this);
    }

    @Override
    public Loginmsg as(Name alias) {
        return new Loginmsg(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Loginmsg rename(String name) {
        return new Loginmsg(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Loginmsg rename(Name name) {
        return new Loginmsg(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
