/*
 * This file is generated by jOOQ.
 */
package com.chen.zhou.liang.lancet.storage.orm.tables;


import com.chen.zhou.liang.lancet.storage.orm.DefaultSchema;
import com.chen.zhou.liang.lancet.storage.orm.tables.records.TranshistoryRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transhistory extends TableImpl<TranshistoryRecord> {

    private static final long serialVersionUID = -1119399364;

    /**
     * The reference instance of <code>transhistory</code>
     */
    public static final Transhistory TRANSHISTORY = new Transhistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TranshistoryRecord> getRecordType() {
        return TranshistoryRecord.class;
    }

    /**
     * The column <code>transhistory.ID</code>.
     */
    public final TableField<TranshistoryRecord, Integer> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>transhistory.creditchange</code>.
     */
    public final TableField<TranshistoryRecord, Float> CREDITCHANGE = createField(DSL.name("creditchange"), org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>transhistory.time</code>.
     */
    public final TableField<TranshistoryRecord, String> TIME = createField(DSL.name("time"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>transhistory</code> table reference
     */
    public Transhistory() {
        this(DSL.name("transhistory"), null);
    }

    /**
     * Create an aliased <code>transhistory</code> table reference
     */
    public Transhistory(String alias) {
        this(DSL.name(alias), TRANSHISTORY);
    }

    /**
     * Create an aliased <code>transhistory</code> table reference
     */
    public Transhistory(Name alias) {
        this(alias, TRANSHISTORY);
    }

    private Transhistory(Name alias, Table<TranshistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Transhistory(Name alias, Table<TranshistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Transhistory(Table<O> child, ForeignKey<O, TranshistoryRecord> key) {
        super(child, key, TRANSHISTORY);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Transhistory as(String alias) {
        return new Transhistory(DSL.name(alias), this);
    }

    @Override
    public Transhistory as(Name alias) {
        return new Transhistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transhistory rename(String name) {
        return new Transhistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transhistory rename(Name name) {
        return new Transhistory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Float, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
